### ISSUE TITLE
running nb2workflow fails on python 3.12

### ISSUE THREAD

**Issue by okolo** [oda-hub/nb2workflow#113]
nbadapter.py uses papermill module which seem to fail on python 3.12:

from nb2workflow.service import main
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.12/site-packages/nb2workflow/service.py", line 13, in <module>
    from nb2workflow import ontology, publish, schedule
  File "/opt/conda/lib/python3.12/site-packages/nb2workflow/ontology.py", line 6, in <module>
    import nb2workflow.nbadapter as nbadapter
  File "/opt/conda/lib/python3.12/site-packages/nb2workflow/nbadapter.py", line 21, in <module>
    import papermill as pm
  File "/opt/conda/lib/python3.12/site-packages/papermill/__init__.py", line 3, in <module>
    from .exceptions import PapermillException, PapermillExecutionError
  File "/opt/conda/lib/python3.12/site-packages/papermill/exceptions.py", line 3, in <module>
    from ansiwrap import strip_color
  File "/opt/conda/lib/python3.12/site-packages/ansiwrap/__init__.py", line 1, in <module>
    from .core import *
  File "/opt/conda/lib/python3.12/site-packages/ansiwrap/core.py", line 6, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'

**Comment by okolo** [comment]
The same code works without errors on python 3.11.6

**Comment by volodymyrss** [comment]
> So let's wait until all dependencies are adapted to 3.12 @volodymyrss your opinion?

yes sure

**Comment by dsavchenko** [comment]
It's still not resolved without https://github.com/oda-hub/nb2workflow/pull/115
As soon as I check it live, I will request the review
