### ISSUE TITLE
Properly treat the case if parameter default is None (but it's annotated)

### ISSUE THREAD

**Issue by dsavchenko** [oda-hub/nb2workflow#136]
Seems that there could be a use-case when this is done by intention.

Otherwise, either prevent with some validation or at least give details in response
Currently, this causes something like 
```
2024-01-29 15:47:58,979 - nb2workflow.nbadapter - DEBUG - cast 60.076524722222224 {'default_value': None, 'python_type': <class 'NoneType'>, 'name': 'DEC', 'comment': 'h
ttp://odahub.io/ontology#PointOfInterestDEC', 'owl_type': 'http://odahub.io/ontology#PointOfInterestDEC', 'extra_ttl': '\n', 'value': None}
2024-01-29 15:47:58,979 - nb2workflow.service - ERROR - Exception on /api/v1.0/get/GAIA_continuum_spectra [GET]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/conda/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/conda/lib/python3.10/site-packages/flasgger/utils.py", line 305, in wrapper
    return function(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/flask_caching/__init__.py", line 399, in decorated_function
    rv = self._call_fn(f, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/flask_caching/__init__.py", line 175, in _call_fn
    return ensure_sync(fn)(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/nb2workflow/service.py", line 431, in workflow_func
    return workflow(target)
  File "/opt/conda/lib/python3.10/site-packages/nb2workflow/service.py", line 273, in workflow
    interpreted_parameters = nba.interpret_parameters(request.args)
  File "/opt/conda/lib/python3.10/site-packages/nb2workflow/nbadapter.py", line 381, in interpret_parameters
    request_parameters[arg] = cast_parameter(parameters.get(arg),expected_parameters.get(arg))
  File "/opt/conda/lib/python3.10/site-packages/nb2workflow/nbadapter.py", line 77, in cast_parameter
    return par['python_type'](x)
TypeError: NoneType takes no arguments
```

**Comment by dsavchenko** [comment]
This issue is in-line with https://github.com/oda-hub/nb2workflow/issues/60

**Comment by dsavchenko** [comment]
May require changes in all stack if we decide to allow None/NaN

**Comment by volodymyrss** [comment]
Allowing `None` for value means changing type to equivalent Option type.
As so, it could make sense, but it can introduce complexities which are hard to debug.
If we try this, we should probably add additional type to distinguish parameters which are Optional, and avoid breaking behavior for non-optional parameters.

**Comment by dsavchenko** [comment]
TODO: check how galaxy deals with this kind of issues (if it is)
