### ISSUE TITLE
[Galaxy] Exception if output is not annotated

### ISSUE THREAD

**Issue by dsavchenko** [oda-hub/nb2workflow#194]
```
2024-08-16 14:35:54,553 ERROR cli  unexpected exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/odabot/cli.py", line 868, in make_galaxy_tools
    to_galaxy(input_path=wf_repo_dir,
  File "/usr/local/lib/python3.9/site-packages/nb2workflow/galaxy.py", line 600, in to_galaxy
    script_str = _nb2script(nba, ontology_path)
  File "/usr/local/lib/python3.9/site-packages/nb2workflow/galaxy.py", line 203, in _nb2script
    outp = GalaxyOutput.from_inspect(vv, ontology_path=ontology_path, dprod=nba.name)
  File "/usr/local/lib/python3.9/site-packages/nb2workflow/galaxy.py", line 170, in from_inspect
    if onto.is_data_product(owl_uri, include_parameter_products=False):
  File "/usr/local/lib/python3.9/site-packages/oda_api/ontology_helper.py", line 404, in is_data_product
    if owl_uri.startswith("http"): owl_uri = f"<{owl_uri}>"
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by dsavchenko** [comment]
Also, if something is annotated as data-product, but there is no oda-api   - it will fail because there is no CustomJSONEncoder
