### ISSUE TITLE
/api/v1.0/options return 500 when notebook is executing in async

### ISSUE THREAD

**Issue by dsavchenko** [oda-hub/nb2workflow#28]
Example internal exception 
```
2022-08-23 17:22:45,406 - nb2workflow.service - ERROR - Exception on /api/v1.0/options [GET]
Traceback (most recent call last):
  File "/home/dsavchenko/Projects/cloud/nb2workflow/.venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dsavchenko/Projects/cloud/nb2workflow/.venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dsavchenko/Projects/cloud/nb2workflow/.venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dsavchenko/Projects/cloud/nb2workflow/.venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dsavchenko/Projects/cloud/nb2workflow/nb2workflow/service.py", line 466, in workflow_options
    return jsonify(dict([
  File "/home/dsavchenko/Projects/cloud/nb2workflow/nb2workflow/service.py", line 469, in <listcomp>
    dict(output=nba.extract_output_declarations(),
  File "/home/dsavchenko/Projects/cloud/nb2workflow/nb2workflow/nbadapter.py", line 408, in extract_output_declarations
    nb=self.read()
  File "/home/dsavchenko/Projects/cloud/nb2workflow/nb2workflow/nbadapter.py", line 187, in read
    return nbformat.reads(open(self.notebook_fn).read(), as_version=4)
FileNotFoundError: [Errno 2] No such file or directory: 'notebooks/lightcurve.ipynb'
```

**Comment by volodymyrss** [comment]
what is the repository you use? does it have notebooks/lightcurve.ipynb in there?

**Comment by dsavchenko** [comment]
I use my https://renkulab.io/gitlab/dsavchenko/mmoda-nb2workflow-example
Of course, it has this file. And request works perfectly as far as the notebook isn't running in async at the moment.
I haven't found the reason yet

**Comment by volodymyrss** [comment]
probably directory changed at some point
