### ISSUE TITLE
requirement breaks flask

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/nb2workflow#43]
nb2workflow requires werkzeug==2.0.3 but this version conflicts with flask import 

Try to release this requirement

# Advances Domain

Mention the Domain this issue addresses, e.g.: 

* UX
* resilience
* community-expanding feature

**Comment by volodymyrss** [comment]
We are running multiple containers with this code. Please try to provide more precise description, in particular all of your requirements, best - your container.

**Comment by ferrigno** [comment]
I prefer to avoid the burden of Dockers, I made a fresh virtual environment and report below the commands and relevant outputs

virtualenv testNB2WKF
activate testNB2WKF/
source testNB2WKF/bin/activate
pip install nb2workflow
pip install flask
`
....
`ERROR: nb2workflow 1.3.34 has requirement werkzeug==2.0.3, but you'll have werkzeug 2.2.2 which is incompatible.
`
``pip install nb2workflow

...

`ERROR: flask 2.2.2 has requirement Werkzeug>=2.2.2, but you'll have werkzeug 2.0.3 which is incompatible.

python -m flask

...
TypeError: __init__() got an unexpected keyword argument 'unbound_message'

`pip install rdflib requests cwltool oda-knowledge-base (see the issue on odakb repoitory)

ERROR: nbconvert 7.2.5 has requirement mistune<3,>=2.0.3, but you'll have mistune 0.8.4 which is incompatible.

`python -m odakb
...
`TypeError: __init__() got an unexpected keyword argument 'unbound_message'


pip install mistune Werkzeug --upgrade
...
ERROR: schema-salad 8.3.20221115203138 has requirement mistune<0.9,>=0.8.1, but you'll have mistune 2.0.4 which is incompatible.
ERROR: nb2workflow 1.3.34 has requirement werkzeug==2.0.3, but you'll have werkzeug 2.2.2 which is incompatible.
...

ipython
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.6.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import flask

In [2]: import odakb as kb

In [3]: import nb2workflow


All imports now work.

So you should probably remove the version requirement for mistune and werkzeug as they do not seem to create errors.

**Comment by volodymyrss** [comment]
> I prefer to avoid the burden of Dockers

Isn't it ironic that dockers were made largely made to, and in particular adopted here precisely to prevent the kind of issues you are having?

As of now, there is a reason for these requirements, and an update can not be taken lightly.

We can think of making an update to the version together with it's requirements, but it needs to be thought-through and made safely.

**Comment by volodymyrss** [comment]
> So you should probably remove the version requirement for mistune and werkzeug as they do not seem to create errors.

Thinking back, there is indeed a very particular reason why we should not remove this constraint.

> pip install nb2workflow
> pip install flask

By the way, you not really expect this to work in general, since it might end up with conflicting requirements (and it does)

> see the issue on odakb repoitory

please refer to the issue

**Comment by ferrigno** [comment]
>please refer to the issue
https://github.com/oda-hub/oda-kb/issues/2

**Comment by ferrigno** [comment]
update with a fresh virtualenv using python 3.9

when running nbinspect using 
 werkzeug 2.0.3
I get
Traceback (most recent call last):
  File "/home/ferrigno/.venv/workflows/bin/nbinspect", line 5, in <module>
    from nb2workflow.nbadapter import main_inspect
  File "/home/ferrigno/.venv/workflows/lib/python3.9/site-packages/nb2workflow/nbadapter.py", line 31, in <module>
    from nb2workflow.json import CustomJSONEncoder
  File "/home/ferrigno/.venv/workflows/lib/python3.9/site-packages/nb2workflow/json.py", line 8, in <module>
    from oda_api.json import CustomJSONEncoder as MMODAJSONEncoder
  File "/home/ferrigno/.venv/workflows/src/oda-api/oda_api/json.py", line 1, in <module>
    from flask.json import JSONEncoder
  File "/home/ferrigno/.venv/workflows/lib/python3.9/site-packages/flask/__init__.py", line 1, in <module>
    from . import json as json
  File "/home/ferrigno/.venv/workflows/lib/python3.9/site-packages/flask/json/__init__.py", line 6, in <module>
    from ..globals import current_app
  File "/home/ferrigno/.venv/workflows/lib/python3.9/site-packages/flask/globals.py", line 45, in <module>
    app_ctx: AppContext = LocalProxy(  # type: ignore[assignment]
TypeError: __init__() got an unexpected keyword argument 'unbound_message'

I had to issue 
pip install flask --upgrade
to have it working but there is this working
ERROR: nb2workflow 1.3.45 has requirement werkzeug==2.0.3, but you'll have werkzeug 2.3.7 which is incompatible.
ERROR: cdci-data-analysis 1.3.5 has requirement werkzeug==2.0.3, but you'll have werkzeug 2.3.7 which is incompatible.

I suggest to add a note in installation at least
